# 1. Basics of Python

## Table of Contents

1: Data Types in Python <br>
2: Working with Strings <br>
3: Lists, Dictionaries, Sets and Tuples <br>
4: Loops & Conditions <br>
5: Functions <br>
6: Classes <br>
7: Debugging <br>
8: Libraries <br>
9: Basic Numpy

<hr style="height:3px">

## 1. Basic Data Types in Python

In [1]:
integer = 5
floats = 5.2
string = 'some text'
boolean = True

print(type(integer))
print(type(floats))
print(type(string))
print(type(boolean))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


<hr style="height:3px">

## 2. Working with Strings in Python
<pre><code>
We have different kinds of strings in Python

Normal string:           print('this is just a normal string')
f-strings (Formatted):   print(f'some text with a {variable} somewhere') 
r-strings (Raw):         print(r'some text with escape \n symbols in it') 
</pre></code>

In [1]:
print('normal: this is just a normal string')
variable = 'variable'
print(f'f-string: some text that can contain a {variable} somewhere') 
print(r'r-string: some text with escape \n symbols in it')
print('Because \n in a normal string means a line-break')

normal: this is just a normal string
f-string: some text that can contain a variable somewhere
r-string: some text with escape \n symbols in it
Because 
 in a normal string means a line-break


In [3]:
print('this is not an f-string, so {variable} will not be accepted')

this is not an f-string, so {variable} will not be accepted


In [4]:
print('this is not an r-string so my escape symbols \n will be interpreted and will not make a new line')
print('escape characters allow to e.g. display an apostrof \' without ending the string')

this is not an r-string so my escape symbols 
 will be interpreted and will not make a new line
escape characters allow to e.g. display an apostrof ' without ending the string


#### Escape Sequences
<pre><code>\n  NEW LINE
\t  TAB
\\  BACKSLASH
\'  SINGLE QUOTE
\"  DOUBLE QUOTE
</pre></code>

In [5]:
print('This is a linebreak: \n and this is a tab: \t doing two \\ will just show one \
and we avoid ending the string by putting a \\\' before an apostrof')

This is a linebreak: 
 and this is a tab: 	 doing two \ will just show one and we avoid ending the string by putting a \' before an apostrof


<hr style="height:3px">

## 3. Lists, Dictionaries, Sets and Tuples
<pre><code>
We have 4 different kinds of data structures in Python

[Lists]         ['Contains a list of items']
{Dictionaries}  {'contains a key': 'and a value'}
{Sets}          {'A bit like a list, but any item can only occur once}
(Tuples)        ('Also like a list, but you can't change the values')
</pre></code>

In [6]:
my_list = [1, 2, 3, 4, 4, 4, 2, 'a', 'b', 'a']
my_dictionary = {'first': 'value', 'second': 'item', 'etc': 'etc'}
my_set = set(my_list)
my_tuple = (1, 2, 3, 4, 4, 4, 2, 'a', 'b', 'a')
my_list, my_dictionary, my_set, my_tuple

([1, 2, 3, 4, 4, 4, 2, 'a', 'b', 'a'],
 {'first': 'value', 'second': 'item', 'etc': 'etc'},
 {1, 2, 3, 4, 'a', 'b'},
 (1, 2, 3, 4, 4, 4, 2, 'a', 'b', 'a'))

In [7]:
# Slicing - Remember first number includes (2) second number exluded (6)
my_list[2:6]

[3, 4, 4, 4]

In [8]:
my_dictionary['second']

'item'

In [9]:
my_set # Notice that all duplicate values are removed

{1, 2, 3, 4, 'a', 'b'}

In [10]:
my_list[5] = 1 # NO ERROR
print(my_list[5])
my_tuple[5] = 1 # ERROR

1


TypeError: 'tuple' object does not support item assignment

<hr style="height:3px">

## 4: Loops & Conditions

We have two different kinds of loops: for & while

In [11]:
for i in range(10):
    print(i**2, end=" ")

0 1 4 9 16 25 36 49 64 81 

In [12]:
for x, y in zip(range(1, 10), range(11, 20)):
    print(x, y, "\n", end="")

1 11 
2 12 
3 13 
4 14 
5 15 
6 16 
7 17 
8 18 
9 19 


### List Comprehension
Not important at all - just an alternative way that is slightly shorter

In [13]:
# List comprehension
my_listcomprehension = [i**2 for i in range(10)]

# Alternative
my_list = []
for i in range(10):
    my_list.append(i**2)

my_listcomprehension == my_list

True

### While Loops

In [14]:
i = 0
while i < 10:
    print(i, end=" ")
    i = i + 1

0 1 2 3 4 5 6 7 8 9 

### Conditions

In [15]:
variable = 2

if variable == 2:
    # Do something
    print('Variable is equal to two')
elif variable > 2:
    # Do something
    print('Variable is higher than two')
else:
    # Do something else
    print('Variable is less than two')

Variable is equal to two


### Sidenote: Assignment versus Evaluation
Short note: Remember that one equal sign (=) is different from (==).

One equal sign = Assigning some variable <br>
Two equal signs == Evaluating if two things are equal <br>
Exclamation and equal != Evaluating if two things are NOT equal

In [16]:
my_variable = 'hello'
my_variable == 'hello', my_variable == 'hey', my_variable != 'hey'

(True, False, True)

In [17]:
# List comprehension
my_listcomprehension = [i**2 for i in range(10)]

# Alternative
my_list = []
for i in range(10):
    my_list.append(i**2)

my_listcomprehension == my_list

True

### Assignment versus Evaluation
Short note: Remember that one equal sign (=) is different from (==).
One equal sign = Assigning some variable <br>
Two equal signs == Evaluating if two things are equal <br>
Exclamation and equal != Evaluating if two things are NOT equal



In [18]:
my_variable = 'hello'
my_variable == 'hello', my_variable == 'hey', my_variable != 'hey'

(True, False, True)

<hr style="height:3px">

## 5. Functions

The basic structure of defining a function (NB: you are very unlikely to use \*args and \*\*kwargs) <br>
\*args = arguments <br>
\*\*kwargs = keyword arguments
<pre><code>
<b>def</b> function_name(parameter1, <i>*args, **kwargs</i>):
    """Function string text that describes what the function does.
       Very important when you're working on projects others will use.
       However, we are most likely too lazy to get this done.
       This text will be shown if you write help(functionName)."""
       
    # Your code goes here:
    <i>square</i> = parameter1 ** 2
    <b>return</b> <i>square</i>
</pre></code>

<br>
Note that the <i>return</i> statements is what variable the function gives you back.

In [19]:
# Simple example of getting circumference of a circle based on the radius
def get_circumference(radius):
    """This function calculates the circumference of a circle based on the radius"""
    circumference = radius * 2 * 3.14
    return circumference

help(get_circumference)

Help on function get_circumference in module __main__:

get_circumference(radius)
    This function calculates the circumference of a circle based on the radius



In [20]:
circumference = get_circumference(2)
circumference

12.56

<b>Positional parameters</b><br>
A function can also have <i>positional parameters</i>. <br>
If you do not explicitly state the input for these positional arguments, the function chooses a predefined input.

In [21]:
def future_value(pv, interest=0.05, years=10, n=1):
    fv = pv * (1+(interest/n))**(n*years)
    return round(fv, 2)

fv1 = future_value(100)
fv2 = future_value(100, 0.10, 2, 2)
fv3 = future_value(pv=100, interest=0.2, years=6)
fv4 = future_value(100, interest=0.8, years=2)

fv1, fv2, fv3, fv4

(162.89, 121.55, 298.6, 324.0)

In [22]:
# Error: positional argument follows keyword argument
fv5 = future_value(pv=100, interest=0.8, 2)

SyntaxError: positional argument follows keyword argument (<ipython-input-22-efc57dd28984>, line 2)

<b>Lambda functions (NOT IMPORTANT)</b><br>
<ul>
This is just a different way to define functions. <br>
A lambda function does NOT have any extra uses that a normal function does not have. <br>
A lambda function is just a shortcut to write a normal function, that can be useful to save a few lines of code 
in some cases where you just have to define a single function. <br>
It has less functionality, but can be written in one line just. <br>
No reason to learn this for simple Python usage. <br>
Many people like to use it in pandas when you use .apply() - however, you can also just use a normal function instead of a lambda function.
</ul>

In [23]:
# Using just one line - compare to the 'def get_circumference' syntax above
lambda_circumference = lambda radius: radius * 2 * 3.14
circumference = lambda_circumference(2)
circumference

12.56

In [24]:
# pandas example
import pandas as pd
data = pd.read_csv('Datasets/titanic.csv')
data.head()

Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2         1       3                              Miss. Laina Heikkinen   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4         0       3                            Mr. William Henry Allen   

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0    male  22.0                        1                        0   7.2500  
1  female  38.0                        1                        0  71.2833  
2  female  26.0                        0                        0   7.9250  
3  female  35.0                        1                        0  53.1000  
4    male  35.0                        0                        0   8.0500

In [25]:
# Lambda function
data['Title'] = data['Name'].apply(lambda name: name.split(' ')[0])
data.head()

Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2         1       3                              Miss. Laina Heikkinen   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4         0       3                            Mr. William Henry Allen   

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  \
0    male  22.0                        1                        0   7.2500   
1  female  38.0                        1                        0  71.2833   
2  female  26.0                        0                        0   7.9250   
3  female  35.0                        1                        0  53.1000   
4    male  35.0                        0                        0   8.0500   

   Title  
0    Mr.  
1   Mrs.  
2  Miss.  
3   Mrs.  
4    Mr.

In [26]:
# Normal function - SAME (with two more lines of code - however, this is not slower)
def split_name(name):
    return name.split(' ')[0]

data['Title'] = data['Name'].apply(split_name)
data.head()

Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2         1       3                              Miss. Laina Heikkinen   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4         0       3                            Mr. William Henry Allen   

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  \
0    male  22.0                        1                        0   7.2500   
1  female  38.0                        1                        0  71.2833   
2  female  26.0                        0                        0   7.9250   
3  female  35.0                        1                        0  53.1000   
4    male  35.0                        0                        0   8.0500   

   Title  
0    Mr.  
1   Mrs.  
2  Miss.  
3   Mrs.  
4    Mr.

<hr style="height:3px">

## 6. Classes
<pre><code>
<b>class</b> MyClass:
    
    def __init__(self, variable1, variable2, ... variable_n):
        self.variable1 = variable1
        self.variable2 = variable2
        self.variable_n = variable_n
    
    def my_function(self, variable1):
        some_code
        return some_stuff
</pre></code>

In [27]:
import numpy as np
import matplotlib.pyplot as plt

class Regression:
    
    def __init__(self, type):
        assert type in ['linear', 'multivariate'], 'Type not valid'
        self.type = type
    
    
    def fit(self, X, y):
        if self.type == 'linear':
            
            SS_Xy = np.sum(y * X - np.size(X) * np.mean(y) * np.mean(X))
            SS_XX = np.sum(X * X - np.size(X) * np.mean(X) * np.mean(X))

            b_1 = SS_Xy / SS_XX
            b_0 = np.mean(y) - b_1 * np.mean(X)

            self.coefficients_ = (b_1, b_0)
            
            return b_1, b_0

        if self.type == 'multivariate':
            print('Too come!')
            return None
    
    
    def predict(self, X):
        prediction = self.coefficients_[0] * X + self.coefficients_[1]
        return prediction
    
    
    def plot(self):
        X = np.arange(0, 10)
        y = X * self.coefficients_[0] + self.coefficients_[1]
        plt.plot(X, y, '-')
        plt.show()
        

# Let's initialize our model
linear = Regression(type='linear')


# Let's make some data we can use as input
X = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])


# Let's fit the model to this data and print out the coefficients
linear.fit(X, y)
print(linear.coefficients_)


# We can also predict what the output would be for a new input
prediction = linear.predict(12)
print(f'We predict: {prediction} for input 12')


# We can also plot model on a graph
linear.plot()


# Or choose a different kind of type for our model - but it has not been finished yet :-(
multiple = Regression(type='multivariate')
multiple.fit(X, y)


(2.0, 0.0)
We predict: 24.0 for input 12


<Figure size 640x480 with 1 Axes>

Too come!


<hr style="height:3px">

## 7: Debugging 

In [28]:
# Syntax error
def error_function()
    pass

SyntaxError: invalid syntax (<ipython-input-28-f045a14d6f63>, line 2)

In [29]:
# Type Error
my_tuple[5] = 1 # ERROR

TypeError: 'tuple' object does not support item assignment

In [30]:
# Type Error
5 / '4'

TypeError: unsupported operand type(s) for /: 'int' and 'str'

In [31]:
# ZeroDivisionError
5 / 0

ZeroDivisionError: division by zero

In [32]:
# Try / Except
variable = 0

try:
    print(5 / variable)
except ZeroDivisionError:
    print(0)

0


## 8: Libraries 

In [33]:
import numpy as np
import pandas as pd
from sklearn.ensemble import AdaBoostClassifier
import matplotlib.pyplot as plt

## 9: Basic Numpy

In [34]:
# Aranges a list from start to stop
my_list = np.arange(10)
my_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
my_list[:3]

array([0, 1, 2])

In [36]:
my_list[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
my_list[2:10:2]

array([2, 4, 6, 8])

In [38]:
my_matrix = np.arange(100).reshape(10,10)
my_matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [39]:
my_matrix[:, 1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [40]:
my_matrix[:, 1:3]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42],
       [51, 52],
       [61, 62],
       [71, 72],
       [81, 82],
       [91, 92]])

In [41]:
my_matrix[:, [1,3,8]]

array([[ 1,  3,  8],
       [11, 13, 18],
       [21, 23, 28],
       [31, 33, 38],
       [41, 43, 48],
       [51, 53, 58],
       [61, 63, 68],
       [71, 73, 78],
       [81, 83, 88],
       [91, 93, 98]])

In [42]:
my_matrix[[1,3,8], :]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [43]:
my_matrix[1:8:2, 3:10:2]

array([[13, 15, 17, 19],
       [33, 35, 37, 39],
       [53, 55, 57, 59],
       [73, 75, 77, 79]])